OneDrive/Desktop/divyang_project/CYBERCOP/CYBERCOP/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
   
    
    path('',include('myapp.urls')),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

OneDrive/Desktop/divyang_project/CYBERCOP/myapp/urls.py
from django.urls import path

from myapp.EditResultView import EditResultView
from . import hod_views,staff_views,student_views
from .views import home, login, logout,forgot_password,PasswordResetDoneView,CustomPasswordResetConfirmView
from rest_framework_simplejwt.views import TokenRefreshView

urlpatterns = [
    path('', home, name='home'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
   
   
#      path('document_dashboard/<int:user_id>/',document_dashboard, name='document_dashboard'),
      path('student/document/<int:document_id>/delete/', student_views.delete_document, name='delete_document'),
   path(' download/<int:document_id>/', student_views.download_decrypted_document, name='download_decrypted_document'),
#    path('upload_document/<int:user_id>/', upload_document, name='upload_document'),
   path('forgot-password/', forgot_password, name='forgot_password'),
    path('reset-password/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='reset_password_confirm'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
     path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
   

#hod urls
   
    path("admin/home/<int:user_id>/", hod_views.admin_home, name='admin_home'),  
    path("staff/add/<int:user_id>/", hod_views.add_staff, name='add_staff'),
    path("course/add/<int:user_id>/", hod_views.add_course, name='add_course'),
    path("send_student_notification/<int:user_id>/", hod_views.send_student_notification,
         name='send_student_notification'),
    path('send_staff_notification/<int:user_id>/', hod_views.send_staff_notification, name='send_staff_notification'),

    path("add_session/<int:user_id>/", hod_views.add_session, name='add_session'),
    path("admin_notify_student/<int:user_id>/", hod_views.admin_notify_student,
         name='admin_notify_student'),
    path("admin_notify_staff/<int:user_id>/", hod_views.admin_notify_staff,
         name='admin_notify_staff'),
     path('admin/view/profile/<int:user_id>/', hod_views.admin_view_profile, name='admin_view_profile'),
    path("check_email_availability", hod_views.check_email_availability,
         name="check_email_availability"),
    path("session/manage/", hod_views.manage_session, name='manage_session'),
    path("session/edit/<int:session_id>",
         hod_views.edit_session, name='edit_session'),
    
    path("student/add/<int:user_id>/", hod_views.add_student, name='add_student'),
    path("subject/add/<int:user_id>/", hod_views.add_subject, name='add_subject'),
    path("staff/manage/<int:user_id>/", hod_views.manage_staff, name='manage_staff'),
    path("student/manage/<int:user_id>/", hod_views.manage_student, name='manage_student'),
    path("course/manage/", hod_views.manage_course, name='manage_course'),
    path("subject/manage/", hod_views.manage_subject, name='manage_subject'),
    path("staff/edit/<int:user_id>/", hod_views.edit_staff, name='edit_staff'),
    path("staff/delete/<int:user_id>/",
         hod_views.delete_staff, name='delete_staff'),

    path("course/delete/<int:course_id>/",
         hod_views.delete_course, name='delete_course'),

    path("subject/delete/<int:subject_id>/",
         hod_views.delete_subject, name='delete_subject'),

    path("session/delete/<int:session_id>/",
         hod_views.delete_session, name='delete_session'),

    path("student/delete/<int:user_id>/",
         hod_views.delete_student, name='delete_student'),
    path("student/edit/<int:user_id>/",
         hod_views.edit_student, name='edit_student'),
    path("course/edit/<int:course_id>/",
         hod_views.edit_course, name='edit_course'),
    path("subject/edit/<int:subject_id>/",
         hod_views.edit_subject, name='edit_subject'),

     #student
      
    path("student/home/<int:user_id>/", student_views.student_home, name='student_home'),
 
    path("student/view/profile/<int:user_id>/", student_views.student_view_profile,
         name='student_view_profile'),
    path("student/fcmtoken/", student_views.student_fcmtoken,
         name='student_fcmtoken'),
    path("student/view/notification/<int:user_id>/", student_views.student_view_notification,
         name="student_view_notification"),
    path('student/view/result/<int:user_id>/', student_views.student_view_result,
         name='student_view_result'),
     path('student/document/<int:user_id>/', student_views.document_upload_student, name='document_upload_student'),
     
     #staff
      path('document-upload-teacher/<int:user_id>/', staff_views.document_upload_teacher, name='document_upload_teacher'),
     path("staff/home/<int:user_id>/", staff_views.staff_home, name='staff_home'),
    path("staff/view/profile/<int:user_id>/", staff_views.staff_view_profile,
         name='staff_view_profile'),
    path("staff/get_students/", staff_views.get_students, name='get_students'),
    path("staff/fcmtoken/", staff_views.staff_fcmtoken, name='staff_fcmtoken'),
    path("staff/view/notification/<int:user_id>/", staff_views.staff_view_notification,
         name="staff_view_notification"),
   path('staff/result/add/<int:user_id>/', staff_views.staff_add_result, name='staff_add_result'),
    path("staff/result/edit/<int:user_id>/", EditResultView.as_view(),
         name='edit_student_result'),
    path('staff/result/fetch/<int:user_id>/', staff_views.fetch_student_result,
         name='fetch_student_result'),

]

OneDrive/Desktop/divyang_project/CYBERCOP/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
   
    
    path('',include('myapp.urls')),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

OneDrive/Desktop/divyang_project/myapp/urls.py
from django.urls import path

from myapp.EditResultView import EditResultView
from . import hod_views,staff_views,student_views
from .views import home, login, logout,forgot_password,PasswordResetDoneView,CustomPasswordResetConfirmView
from rest_framework_simplejwt.views import TokenRefreshView

urlpatterns = [
    path('', home, name='home'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
   
   
#      path('document_dashboard/<int:user_id>/',document_dashboard, name='document_dashboard'),
      path('student/document/<int:document_id>/delete/', student_views.delete_document, name='delete_document'),
   path(' download/<int:document_id>/', student_views.download_decrypted_document, name='download_decrypted_document'),
#    path('upload_document/<int:user_id>/', upload_document, name='upload_document'),
   path('forgot-password/', forgot_password, name='forgot_password'),
    path('reset-password/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='reset_password_confirm'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
     path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
   

#hod urls
   
    path("admin/home/<int:user_id>/", hod_views.admin_home, name='admin_home'),  
    path("staff/add/<int:user_id>/", hod_views.add_staff, name='add_staff'),
    path("course/add/<int:user_id>/", hod_views.add_course, name='add_course'),
    path("send_student_notification/<int:user_id>/", hod_views.send_student_notification,
         name='send_student_notification'),
    path('send_staff_notification/<int:user_id>/', hod_views.send_staff_notification, name='send_staff_notification'),

    path("add_session/<int:user_id>/", hod_views.add_session, name='add_session'),
    path("admin_notify_student/<int:user_id>/", hod_views.admin_notify_student,
         name='admin_notify_student'),
    path("admin_notify_staff/<int:user_id>/", hod_views.admin_notify_staff,
         name='admin_notify_staff'),
     path('admin/view/profile/<int:user_id>/', hod_views.admin_view_profile, name='admin_view_profile'),
    path("check_email_availability", hod_views.check_email_availability,
         name="check_email_availability"),
    path("session/manage/", hod_views.manage_session, name='manage_session'),
    path("session/edit/<int:session_id>",
         hod_views.edit_session, name='edit_session'),
    
    path("student/add/<int:user_id>/", hod_views.add_student, name='add_student'),
    path("subject/add/<int:user_id>/", hod_views.add_subject, name='add_subject'),
    path("staff/manage/<int:user_id>/", hod_views.manage_staff, name='manage_staff'),
    path("student/manage/<int:user_id>/", hod_views.manage_student, name='manage_student'),
    path("course/manage/", hod_views.manage_course, name='manage_course'),
    path("subject/manage/", hod_views.manage_subject, name='manage_subject'),
    path("staff/edit/<int:user_id>/", hod_views.edit_staff, name='edit_staff'),
    path("staff/delete/<int:user_id>/",
         hod_views.delete_staff, name='delete_staff'),

    path("course/delete/<int:course_id>/",
         hod_views.delete_course, name='delete_course'),

    path("subject/delete/<int:subject_id>/",
         hod_views.delete_subject, name='delete_subject'),

    path("session/delete/<int:session_id>/",
         hod_views.delete_session, name='delete_session'),

    path("student/delete/<int:user_id>/",
         hod_views.delete_student, name='delete_student'),
    path("student/edit/<int:user_id>/",
         hod_views.edit_student, name='edit_student'),
    path("course/edit/<int:course_id>/",
         hod_views.edit_course, name='edit_course'),
    path("subject/edit/<int:subject_id>/",
         hod_views.edit_subject, name='edit_subject'),

     #student
      
    path("student/home/<int:user_id>/", student_views.student_home, name='student_home'),
 
    path("student/view/profile/<int:user_id>/", student_views.student_view_profile,
         name='student_view_profile'),
    path("student/fcmtoken/", student_views.student_fcmtoken,
         name='student_fcmtoken'),
    path("student/view/notification/<int:user_id>/", student_views.student_view_notification,
         name="student_view_notification"),
    path('student/view/result/<int:user_id>/', student_views.student_view_result,
         name='student_view_result'),
     path('student/document/<int:user_id>/', student_views.document_upload_student, name='document_upload_student'),
     
     #staff
      path('document-upload-teacher/<int:user_id>/', staff_views.document_upload_teacher, name='document_upload_teacher'),
     path("staff/home/<int:user_id>/", staff_views.staff_home, name='staff_home'),
    path("staff/view/profile/<int:user_id>/", staff_views.staff_view_profile,
         name='staff_view_profile'),
    path("staff/get_students/", staff_views.get_students, name='get_students'),
    path("staff/fcmtoken/", staff_views.staff_fcmtoken, name='staff_fcmtoken'),
    path("staff/view/notification/<int:user_id>/", staff_views.staff_view_notification,
         name="staff_view_notification"),
   path('staff/result/add/<int:user_id>/', staff_views.staff_add_result, name='staff_add_result'),
    path("staff/result/edit/<int:user_id>/", EditResultView.as_view(),
         name='edit_student_result'),
    path('staff/result/fetch/<int:user_id>/', staff_views.fetch_student_result,
         name='fetch_student_result'),

]

OneDrive/Desktop/divyang_project/CYBERCOP/myapp/models.py
import base64
import os
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
from django.contrib.auth.models import BaseUserManager
from .utils import generate_aes_key
class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)
class Role(models.Model):
    role_choices = [
    ('1', 'Hod'),
    ('2', 'Teacher'),
    ('3', 'Student'),
]
    role=models.CharField(choices=role_choices,max_length=20)
    class Meta:
        managed=True
class Session(models.Model):
    start_year = models.DateField()
    end_year = models.DateField()

    def __str__(self):
        return "From " + str(self.start_year) + " to " + str(self.end_year)
    class Meta:
        managed=True 

class Course(models.Model):
    name = models.CharField(max_length=120)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


       
class CustomUser(AbstractUser):
    gender_choices=[
        ('F','Female'),
        ('M','Male'),
        ('O','Other'),
    ]
    email = models.EmailField(unique=True)  # Ensure email is unique for each user
    USERNAME_FIELD = 'email'  # Use email as the unique identifier for authentication
    REQUIRED_FIELDS = []  # Remove 'email' from REQUIRED_FIELDS since it's already the USERNAME_FIELD
    fcm_token = models.TextField(default="") 
    surname=models.CharField(max_length=20)
    role = models.ManyToManyField(Role,related_name='users')
    session = models.ForeignKey(Session, on_delete=models.DO_NOTHING, null=True)
    gender=models.CharField(max_length=10,choices=gender_choices)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    profile_pic = models.ImageField(upload_to='profile_pics/', blank=True)
    course = models.ForeignKey(Course, on_delete=models.DO_NOTHING, null=True, blank=False)
    groups = models.ManyToManyField('auth.Group', related_name='custom_user_groups')
    user_permissions = models.ManyToManyField('auth.Permission', related_name='custom_user_permissions')
    class Meta:
        managed=True
    objects = CustomUserManager()   
    
  

class Subject(models.Model):
    name = models.CharField(max_length=120)
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Document(models.Model):
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    encrypted_file = models.FileField(upload_to='') 
    encryption_key = models.TextField(blank=True)
    encrypted_data = models.BinaryField(default=b'')
    visible_to_staff = models.BooleanField(default=False)
    visible_to_admin = models.BooleanField(default=False) 
    teacher = models.ForeignKey(CustomUser, related_name='documents_teacher', on_delete=models.CASCADE, null=True, blank=True)
   
    def save(self, *args, **kwargs):
        # Generate encryption key if not provided
        if not self.encryption_key:
            self.encryption_key = base64.b64encode(generate_aes_key()).decode()
       
            super().save(*args, **kwargs)
            
            # Get the role of the owner
            owner_role = self.owner.role.first()
            
            # Check if the owner is a teacher
            if owner_role and owner_role.role == 'teacher':
                self.teacher = self.owner
                self.save(update_fields=['teacher'])  # Save only the 'teacher' field
        else:
            super().save(*args, **kwargs)
        
    class Meta:
        managed=True  


class NotificationStaff(models.Model):
    staff = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class NotificationStudent(models.Model):
    student = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class StudentResult(models.Model):
    student = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    test = models.FloatField(default=0)
    exam = models.FloatField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

OneDrive/Desktop/divyang_project/myapp/templates/staff_template/edit_student_result.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}
{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                    <form method="POST">
                        {% csrf_token %}
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

       
                    <!-- /.card-header -->
                    <!-- form start -->
                    <div class="card-body">


                     

                 {{ form }}

                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" id='update_result' class="btn btn-primary btn-block">Update Result</button>
               
                    </div>
                </form>
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}


{% block custom_js %}
<script>
    $(document).ready(function () {
        $("#id_subject").change(function () {
            fetchStudents();
            });
            $("#id_session_year").change(function () {
                fetchStudents();
                });
   $("#id_student").change(function () {
    fetch_student_result();
                });
                $("#id_exam").hide()
                $("#id_test").hide()
                $("#update_result").hide()
                $('label[for="id_test"]').hide();
                $('label[for="id_exam"]').hide();
        function fetchStudents(){
            var subject = $("#id_subject").val()
            var session = $("#id_session_year").val()
            $("#id_student").html(null)
            if (session.length  == 0 || subject.length == 0 || session < 1 || subject < 1){
                return false;
            }
            $.ajax({
                url: "{% url 'get_students' %}",
                type: 'POST',
                data: {
                    subject: subject,
                    session:session
                }
            }).done(function (response) {
                var json_data = JSON.parse(response)
                if (json_data.length < 1) {
                    alert("No data to display")
                } else {
                    var div_data = "<option>Select Student</option>"

                    for (key in json_data) {
                        div_data += "<option value='" + json_data[key]['id'] + "'>" + json_data[key]['name'] + " </option>"
                    }
             
                    $("#id_student").html(div_data)
                }
            }).fail(function (response) {
                alert("Error in fetching students")
            })
               }

               function fetch_student_result(){
                var student = $("#id_student").val()
                var subject = $("#id_subject").val()
                $("#id_test").val(null)
                $("#id_exam").val(null)
                $("#id_exam").hide()
                $("#update_result").hide()
                $("#id_test").hide()
                $('label[for="id_test"]').hide();
                $('label[for="id_exam"]').hide();
                if (student.length  == 0 || subject.length == 0 || student < 1 || subject < 1){
                    return false;
                }
                $.ajax({
                    url: "{% url 'fetch_student_result' user_id=user_id %}",
                    type: 'POST',
                    data: {
                        user_id:user_id,
                        subject: subject,
                        student:student
                    }
                }).done(function (response) {
                    if (response == 'False') {
                        alert("No data to display")
                    } else {
                        var json_data = JSON.parse(response)
                        
                            $("#id_test").val(json_data['test'])
                            $("#id_exam").val(json_data['exam'])
                            $("#id_exam").show()
                            $("#id_test").show()
                            $("#update_result").show()
                            $('label[for="id_test"]').show();
                            $('label[for="id_exam"]').show();

                    }
                }).fail(function (response) {
                    alert("Error in fetching students")
                })
               }

    })
</script>
{% endblock custom_js %}

OneDrive/Desktop/divyang_project/myapp/templates/staff_template/home_content.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}
{% block content %}
<section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-info">
                    <div class="inner">
                        <h3>{{total_students}}</h3>

                        <p>Total Students</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>
                   
                </div>
            </div>
            
           
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-danger">
                    <div class="inner">
                        <h3>{{total_subject}}</h3>

                        <p>Total Subjects</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-pie-graph"></i>
                    </div>
                   
                </div>
            </div>
            <!-- ./col -->
        </div>
        <!-- /.row -->
        <!-- Main row -->
        <div class="row">
            <div class="col-md-6">
                <!-- LINE CHART -->
                <div class="card card-secondary">
                  <div class="card-header">
                    <h3 class="card-title">{{page_title}}</h3>
    
                    <div class="card-tools">
                      <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                      </button>
                      <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
                    </div>
                  </div>
                  <div class="card-body">
                    <div class="chart">
                      <canvas id="pieChart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
                    </div>
                  </div></div>
                  <!-- /.card-body -->
                </div>
                <div class="col-md-6">
                    <div class="card card-secondary">
              <div class="card-header">
                <h3 class="card-title">{{page_title}}</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                  </button>
                  <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
                </div>
              </div>
              <div class="card-body">
                <div class="chart">
                  <canvas id="barChart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
                </div>
              </div>
              <!-- /.card-body -->
            </div>
                </div>
            <!-- right col -->
        </div>
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>
{% endblock content %}

{% block custom_js %}
  <script>
      $(document).ready(function(){
        var donutData        = {
            labels: ['Attendance', 'Leave'],
            datasets: [
              {
                data:[{{total_attendance}}, {{total_leave}}],
                backgroundColor : ['#00a65a', '#f39c12',],
              }
            ]
          }
        var pieChartCanvas = $('#pieChart').get(0).getContext('2d')
        var pieData        = donutData;
        var pieOptions     = {
          maintainAspectRatio : false,
          responsive : true,
        }
        //Create pie or douhnut chart
        // You can switch between pie and douhnut using the method below.
        var pieChart = new Chart(pieChartCanvas, {
          type: 'pie',
          data: pieData,
          options: pieOptions      
        });

        var subject_list = {{ subject_list|safe|escape }};
       
  
            var barChartData = {
      labels  : subject_list,
      datasets: [
      {
        label               : 'Attendance Per Subject',
        backgroundColor     : '#6c757d',
        borderColor         : 'rgba(60,141,188,0.8)',
        pointRadius          : false,
        pointColor          : '#3b8bba',
        pointStrokeColor    : 'rgba(60,141,188,1)',
        pointHighlightFill  : '#fff',
        pointHighlightStroke: 'rgba(60,141,188,1)',
        data                : attendance_list
      }, 
      
      ]
    }
        var barChartCanvas = $('#barChart').get(0).getContext('2d')
        var temp0 = barChartData.datasets[0]
        //var temp1 = areaChartData.datasets[1]
        barChartData.datasets[0] = temp0
       // barChartData.datasets[1] = temp0
    
    var stackedBarChartOptions = {
      responsive              : true,
      maintainAspectRatio     : false,
      scales: {
        xAxes: [{
          stacked: true,
        }],
        yAxes: [{
          stacked: true
        }]
      }
    }
    
        var barChart = new Chart(barChartCanvas, {
          type: 'bar', 
          data: barChartData,
          options: stackedBarChartOptions
        })
      })

    
  </script>
      <!-- The core Firebase JS SDK is always required and must be listed first -->
      <script src="https://www.gstatic.com/firebasejs/7.23.0/firebase-app.js"></script>

      <!-- TODO: Add SDKs for Firebase products that you want to use
       https://firebase.google.com/docs/web/setup#available-libraries -->
      <script src="https://www.gstatic.com/firebasejs/7.23.0/firebase-analytics.js"></script>
      <script src="https://www.gstatic.com/firebasejs/7.22.1/firebase-messaging.js"></script>
  
  
      <script>
          // Your web app's Firebase configuration
          // For Firebase JS SDK v7.20.0 and later, measurementId is optional
          var firebaseConfig = {
              apiKey: "AIzaSyBarDWWHTfTMSrtc5Lj3Cdw5dEvjAkFwtM",
              authDomain: "sms-with-django.firebaseapp.com",
              databaseURL: "https://sms-with-django.firebaseio.com",
              projectId: "sms-with-django",
              storageBucket: "sms-with-django.appspot.com",
              messagingSenderId: "945324593139",
              appId: "1:945324593139:web:03fa99a8854bbd38420c86",
              measurementId: "G-2F2RXTL9GT"
          };
          // Initialize Firebase
          firebase.initializeApp(firebaseConfig)
          const messaging = firebase.messaging();
          function InitializeFireBaseMessaging() {
              messaging
                  .requestPermission()
                  .then(function () {
                      console.log("Notification Permission");
                      return messaging.getToken();
                  })
                  .then(function (token) {
                      console.log("Token : " + token);
                      sendToServer(token);
                  })
                  .catch(function (reason) {
                      console.log(reason)
                  })
          }
          messaging.onMessage(function (payload) {
              const notificationOption = {
                  body: payload.notification.body,
                  icon: payload.notification.icon,
  
              }
              if (Notification.permission == 'granted') {
                  var notification = new Notification(payload.notification.title, notificationOption);
                  notification.onclick = function (event) {
                      event.preventDefault();
                      window.open(payload.notification.click_action, "_blank");
                      notification.close();
                  }
              }
              console.log(payload);
          });
          messaging.onTokenRefresh(function () {
              messaging.getToken()
                  .then(function (newToken) {
                      console.log("New Token : " + newToken);
                      sendToServer(newToken);

                  })
                  .catch(function (reason) {
                      console.log(reason)
                  })
          })
  
          function sendToServer(token){
            $.ajax({
              url: "{% url 'staff_fcmtoken' %}",
              type: 'POST',
              data: {
                  token: token,
              }
          }).done(function (response) {
   
             
          }).fail(function (response) {
          })

          }
          
          InitializeFireBaseMessaging();
      </script>
{% endblock custom_js %}